name: Release Addon

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package and Upload to Wago.io and CurseForge
        uses: BigWigsMods/packager@master
        env:
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
